image: node:16.13.0

stages:
  - build
  - test
  - docker-build

build:
  stage: build
  image: node:16.13.0
  script:
    - npm install
    - CI=false npm run build
  allow_failure: true

test:
  stage: test
  image: node:16.13.0
  script:
    - npm install
    - npm test

docker-build:
  stage: docker-build
  image: docker
  services:
    - name: docker:dind
      alias: dockerdaemon
  variables:
    DOCKER_HOST: tcp://dockerdaemon:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  allow_failure: true